import { createRequire } from 'node:module';
const require = createRequire('C:/Users/Kenneth Rodas/Documents/GitHub/google-flow-mcp/package.json');
const { chromium } = require('playwright');
const theme = process.argv[2] || 'dark';
const b = await chromium.connectOverCDP('http://127.0.0.1:9222'); const ctx = b.contexts()[0]; const p = await ctx.newPage();
await p.setViewportSize({ width: 390, height: 844 });
await p.addInitScript((t) => { try { localStorage.setItem('eat.theme', t); } catch (e) {} }, theme);
const errors = []; p.on('pageerror', (e) => errors.push(e.message)); p.on('console', (m) => { if (m.type() === 'error') errors.push(m.text().slice(0, 100)); });
await p.goto('http://127.0.0.1:4173/', { waitUntil: 'networkidle' }); await p.waitForTimeout(1200);
const meta = () => p.evaluate(() => document.getElementById('theme-color').content);
console.log('theme-color at top:', await meta(), 'burger x:', Math.round((await p.locator('.burger').boundingBox()).x));
await p.screenshot({ path: `qa/m2-${theme}-top.png` });
await p.click('.burger'); await p.waitForTimeout(700); await p.screenshot({ path: `qa/m2-${theme}-menu.png` });
await p.keyboard.press('Escape'); await p.waitForTimeout(300);
await p.click('.hero .search-input'); await p.waitForTimeout(900); await p.keyboard.type('late', { delay: 30 }); await p.waitForTimeout(400);
await p.screenshot({ path: `qa/m2-${theme}-search.png` });
const panel = await p.locator('.hero .search-panel').boundingBox(); console.log('panel box:', panel && Math.round(panel.y), Math.round(panel.height), 'viewport 844');
await p.keyboard.press('Escape');
await p.evaluate(() => window.scrollTo(0, 1400)); await p.waitForTimeout(600); console.log('theme-color scrolled:', await meta());
await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight)); await p.waitForTimeout(800); await p.screenshot({ path: `qa/m2-${theme}-bottom.png` });
console.log('errors', errors.length, errors.slice(0, 3));
await p.close(); await b.close();
